/*
CREATE A SUDOKU SOLVER USING THE FOLLOWING RULES:
1. NO ROW CAN CONTAIN THE SAME NUMBER
2. NO COLUMN CAN CONTAIN THE SAME NUMBER
3. NO 3X3 BOX CAN CONTAIN THE SAME NUMBER

 MAYBE MAKE IT SO PLAYERS CAN ALSO PLAY THE GAME WHERE IT CREATES A RANDOM SUDOKU GAME
 BASED ON DIFFICULTY(EASY, MEDIUM, HARD) AND IF THEY CANT SOLVE IT THE PROGRAM WILL SOLVE IT FOR THEM

 GOOD LUCK!!!!
 */

  public class Main {
    public static void main(String[] args) {
        GUI gui = new GUI();
        gui.mainFrame();
    }
}